# -*- coding: utf-8 -*-
"""Week6Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1HxOxniR9clXi5ZgQONPy0C_kEMD45w
"""



import pandas as pd
import csv
import matplotlib.pyplot as plt



graphOut = pd.read_csv('/content/outside.csv')
graphIn = pd.read_csv('/content/test.csv')

cutOut = 240
concOut = graphOut.iloc[cutOut:,1]
concIn = graphIn.iloc[cutOut:,1]
part3Out = graphOut.iloc[cutOut:,2]
part25In = graphIn.iloc[cutOut:,5]
part25Out = graphOut.iloc[cutOut:,5]
part3In = graphIn.iloc[cutOut:,2]
tempOut = graphOut.iloc[cutOut:,9]
tempIn = graphIn.iloc[cutOut:,9]
gasOut = graphOut.iloc[cutOut:,10]
gasIn = graphIn.iloc[cutOut:,10]
relHumOut = graphOut.iloc[cutOut:,11]
relHumIn = graphIn.iloc[cutOut:,11]
presOut = graphOut.iloc[cutOut:,12]
presIn = graphIn.iloc[cutOut:,12]
altOut = graphOut.iloc[cutOut:,13]
altIn = graphIn.iloc[cutOut:,13]

timeOut = graphOut.iloc[:,8]
timeIn = graphIn.iloc[:,8]

print(concOut)

plt.figure()
plt.hist(tempIn, 50)

plt.title('Inside Temperature')
plt.ylabel('Frecuency')
plt.xlabel('Temperature in Celsius')
plt.show()

plt.figure()
plt.hist(tempOut, 50)
plt.title('Outside Temperature')
plt.ylabel('Frecuency')
plt.xlabel('Temperature in Celsius')
plt.show()

plt.figure()
plt.hist(concIn, 50)

plt.title('Inside Particle Concentration')
plt.ylabel('Frecuency')
plt.xlabel('Amount of Particles')
plt.show()

plt.figure()
plt.hist(concOut, 50)
plt.title('Outside Particle Concentration')
plt.ylabel('Frecuency')
plt.xlabel('Amount of Particles')
plt.show()

plt.figure()
plt.hist(part3In, 25)

plt.title('Inside Particle 2.5')
plt.ylabel('Frecuency')
plt.xlabel('Number of Particles')
plt.show()

plt.figure()
plt.hist(part3Out, 50)
plt.title('Outside Particle 2.5')
plt.ylabel('Frecuency')
plt.xlabel('Number of Particles')
plt.show()

plt.figure()
plt.hist(part25In, 50)

plt.title('Inside Particle 25')
plt.ylabel('Frecuency')
plt.xlabel('Amount of Particles')
plt.show()

plt.figure()
plt.hist(part25Out, 50)
plt.title('Outside Particle 25')
plt.ylabel('Frecuency')
plt.xlabel('Amount of Particles')
plt.show()

plt.figure()
plt.hist(gasIn, 50)

plt.title('Inside Gas')
plt.ylabel('Frecuency')
plt.xlabel('Amount of Gas')
plt.show()

plt.figure()
plt.hist(gasOut, 12)
plt.title('Outside Gas')
plt.ylabel('Frecuency')
plt.xlabel('Amount of Gas')
plt.show()

plt.figure()
plt.hist(relHumIn, 50)

plt.title('Inside Relative Humidity')
plt.ylabel('Frecuency')
plt.xlabel('Humidity')
plt.show()

plt.figure()
plt.hist(relHumOut, 50)
plt.title('Outside Humidity')
plt.ylabel('Frecuency')
plt.xlabel('Humidity')
plt.show()

plt.figure()
plt.hist(presIn, 50)

plt.title('Inside Pressure')
plt.ylabel('Frecuency')
plt.xlabel('Pressure pascal')
plt.show()

plt.figure()
plt.hist(presOut, 50)
plt.title('Outside Pressure')
plt.ylabel('Frecuency')
plt.xlabel('Pressure pascal')
plt.show()

plt.figure()
plt.hist(altIn, 50)

plt.title('Inside Altitude')
plt.ylabel('Frecuency')
plt.xlabel('Altitude (meters)')
plt.show()

plt.figure()
plt.hist(altOut, 50)
plt.title('Outside Altitude')
plt.ylabel('Frecuency')
plt.xlabel('Altitude (meters)')
plt.show()

"""cutOut = 240
concOut = graphOut.iloc[cutOut:,1]
concIn = graphIn.iloc[cutOut:,1]
part3Out = graphOut.iloc[cutOut:,2]
part25In = graphIn.iloc[cutOut:,5]
part25Out = graphOut.iloc[cutOut:,5]
part3In = graphIn.iloc[cutOut:,2]
tempOut = graphOut.iloc[cutOut:,9]
tempIn = graphIn.iloc[cutOut:,9]
gasOut = graphOut.iloc[cutOut:,10]
gasIn = graphIn.iloc[cutOut:,10]
relHumOut = graphOut.iloc[cutOut:,11]
relHumIn = graphIn.iloc[cutOut:,11]
presOut = graphOut.iloc[cutOut:,12]
presIn = graphIn.iloc[cutOut:,12]
altOut = graphOut.iloc[cutOut:,13]
altIn = graphIn.iloc[cutOut:,13]

timeOut = graphOut.iloc[:,8]
timeIn = graphIn.iloc[:,8]

print(concOut)
"""

import numpy as np
np.mean(concOut)
np.std(concOut)

insideData = [concIn, part3In, part25In, tempIn, gasIn, relHumIn, presIn, altIn]
outsideData = [concOut, part3Out, part25Out, tempOut, gasOut, relHumOut, presOut, altOut]

insideMeanStat = [0,0,0,0,0,0,0,0]
outsideMeanStat = [0,0,0,0,0,0,0,0]

insideSDStat = [0,0,0,0,0,0,0,0]
outsideSDStat = [0,0,0,0,0,0,0,0]

sampleNum = 600 - cutOut

for i in range(0,8):
  insideMeanStat[i] = float(np.mean(insideData[i]))
  outsideMeanStat[i] = float(np.mean(outsideData[i]))

  insideSDStat[i] = float(np.std(insideData[i]))
  outsideSDStat[i] = float(np.std(outsideData[i]))

print(outsideSDStat)
print(insideSDStat)

print(outsideMeanStat)
print(insideMeanStat)

#finding uncertainty

insideMeanUncertainty = [0,0,0,0,0,0,0,0]
outsideMeanUncertainty = [0,0,0,0,0,0,0,0]

for i in range(0,8):

  insideMeanUncertainty[i] = float(insideSDStat[i]/np.sqrt(sampleNum))


  outsideMeanUncertainty[i] = float(outsideSDStat[i]/np.sqrt(sampleNum))
print(insideMeanUncertainty)
print(outsideMeanUncertainty)

#Number of std deviations away (from outside and inside)

import math

#Using smallest standard deviation

differenceSD = [0,0,0,0,0,0,0,0]

for i in range(0,8):
  if (insideSDStat[i] < outsideSDStat[i]) and insideSDStat[i] != 0.0:

    differenceSD[i] = float(np.abs((insideMeanStat[i] - outsideMeanStat[i])/insideSDStat[i]))

  if outsideSDStat[i] != 0.0:

    differenceSD[i] = float(np.abs((insideMeanStat[i] - outsideMeanStat[i])/outsideSDStat[i]))

  else:
    differenceSD[i] = 999

print(differenceSD)

"""Some data points are roughly the same, while others are so dramatically different that there is undeniable evidence that outside is in fact different from the inside.

I do not think we took enough data points to get a gaussian distribution.
"""

#Step 2, Comparing Sensors