# -*- coding: utf-8 -*-
"""Week5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjQzyVShB1cy83fzQuxq5_SW5GHmnwgj
"""

import pandas as pd
import csv
import matplotlib.pyplot as plt

graphOut = pd.read_csv('/content/outside.csv')
graphIn = pd.read_csv('/content/test.csv')
concOut = graphOut.iloc[:,1]
concIn = graphIn.iloc[:,1]
part3Out = graphOut.iloc[:,2]
part25In = graphIn.iloc[:,5]
part25Out = graphOut.iloc[:,5]
part3In = graphIn.iloc[:,2]
tempOut = graphOut.iloc[:,9]
tempIn = graphIn.iloc[:,9]
gasOut = graphOut.iloc[:,10]
gasIn = graphIn.iloc[:,10]
relHumOut = graphOut.iloc[1:,11]
relHumIn = graphIn.iloc[1:,11]
presOut = graphOut.iloc[1:,12]
presIn = graphIn.iloc[1:,12]
altOut = graphOut.iloc[1:,13]
altIn = graphIn.iloc[1:,13]

timeOut = graphOut.iloc[:,8]
timeIn = graphIn.iloc[:,8]

print(concOut)

plt.figure()
plt.plot(tempIn.index, tempIn)
plt.show()
plt.figure()
plt.plot(tempOut.index, tempOut)
plt.show()

plt.figure()
plt.plot(concIn.index, concIn)
plt.show()
plt.figure()
plt.plot(concOut.index, concOut)
plt.show()

plt.figure()
plt.plot(part3In.index, part3In)
plt.show()
plt.figure()
plt.plot(part3Out.index, part3Out)
plt.show()

plt.figure()
plt.plot(part25In.index, part25In)
plt.show()
plt.figure()
plt.plot(part25Out.index, part25Out)
plt.show()

plt.figure()
plt.plot(gasIn.index, gasIn)
plt.show()
plt.figure()
plt.plot(gasOut.index, gasOut)
plt.show()

plt.figure()
plt.plot(relHumIn.index, relHumIn)
plt.show()
plt.figure()
plt.plot(relHumOut.index, relHumOut)
plt.show()

plt.figure()
plt.plot(presIn.index, presIn)
plt.show()
plt.figure()
plt.plot(presOut.index, presOut)
plt.show()

plt.figure()
plt.plot(altIn.index, altIn)
plt.show()
plt.figure()
plt.plot(altOut.index, altOut)
plt.show()

